### ISSUE TITLE
Add Suport for Firefox Sync

### ISSUE THREAD

**Issue by JakobDev** [Rayquaza01/HistoryCleaner#1]
It would be nice, if the number of days are automatic synced with other Computers.

**Comment by herrbrixter** [comment]
In case the addon someday becomes available in Firefox Android, please sync the settings there as well if possible.

**Comment by Rayquaza01** [comment]
Firefox Sync support was actually added a few years back ([in 2020, actually](https://github.com/Rayquaza01/HistoryCleaner/commit/40914462a6cfbc56144383d884757724857b515a), but it's not automatic. In the latest version, the sync buttons (along with import/export buttons) are under the Sync category in the popup.

The reason it's not automatic is that if you're syncing your browsing history, then History Cleaner only needs to be enabled on one device, and the deletions will sync automatically. So I want to support the use case of having History Cleaner enabled on one device, but disabled on another.
