### ISSUE TITLE
Delete download history

### ISSUE THREAD

**Issue by davidhedlund** [Rayquaza01/HistoryCleaner#2]
I suggest that you implement the same functionality as the legacy add-on [Deletebutton](https://addons.mozilla.org/en-US/firefox/addon/deletebutton/) to revive it as a WE in your add-on.

**Comment by davidhedlund** [comment]
I just a WebExtension to delete the download history: [Download History Cleaner (Eraser)](https://addons.mozilla.org/en-US/firefox/addon/download-history-cleaner/)

**Comment by herrbrixter** [comment]
If it only deletes the download history without deleting the downloaded file, then I agree.

**Comment by Rayquaza01** [comment]
An option to clear download history has (finally) been added in version 1.7.0. When enabled, download history is cleared using the same settings as browsing history.

**Comment by davidhedlund** [comment]
> An option to clear download history has (finally) been added in version 1.7.0. When enabled, download history is cleared using the same settings as browsing history.

Good job!

I suggest that you change the main description of the project from
* "Firefox addon that deletes history older than a specified amount of days." to something like
* "Firefox addon that deletes browser and/or download history older than a specified amount of days."
