### ISSUE TITLE
Clean also the downloads history?

### ISSUE THREAD

**Issue by phaolo2** [Rayquaza01/HistoryCleaner#20]
Could you please add an option to clean also the downloads history?
Firefox never does it, for some reason..

**Comment by herrbrixter** [comment]
Don't make this a default. Unlike the history, the downloads are important to me and I have far less downloaded files than internet history. I don't want my downloads like important pictures or documents to be accidentally deleted by Firefox.

**Comment by herrbrixter** [comment]
This is a duplicate of #2
