### ISSUE TITLE
(Solved) Dates Possible?

### ISSUE THREAD

**Issue by CraigS26** [Rayquaza01/HistoryCleaner#35]
FF 123.0.1 ... Save 5 Days - View Last 7 days shows No Dates - Rt Clk Headings-- Added / Modified / Last Visit = No Dates .... Are dates Possible?
**EDIT**: Apparently ESET Security Suite feature - (BPP) Bank Payment & Protection module (hides keystrokes, etc) - blocks this Addon from showing dates. I **DISabled BPP** and .... Most Recent Visit dates showed...  I'll live without Dates....
**EDIT 2**: It gets better .... I RE-Enabled BPP expecting No Dates Again. Last Visit dates STILL Show. So One Disable of BPP Fixed All. 
**DELETE THIS POST as desired.**

**Comment by Rayquaza01** [comment]
Glad you figured out what that problem was!
