### ISSUE TITLE
Getting spammed by notifications

### ISSUE THREAD

**Issue by MightyCreak** [Rayquaza01/HistoryCleaner#36]
Hello!

As written in [this review](https://addons.mozilla.org/fr/firefox/addon/history-cleaner/reviews/2059402/), I get spammed with notifications (I'd say 10 per hour) although I've setup the cleanup to be done every 24h as you can see here:

![image](https://github.com/Rayquaza01/HistoryCleaner/assets/6382548/4066630c-33ab-42cd-bdc6-f0d71c52b073)

Note: I use Firefox Sync and I have 3 or 4 devices with History Cleaner installed on them (I don't know if the settings are also shared or if it's only the extensions).

**Comment by Rayquaza01** [comment]
You have the Trigger Mode set to Idle, not Timer. Idle will trigger every time you leave your computer with no input for the Idle Length (by default, 60 seconds). If you want it to run once every 24 hours, set the Trigger Mode to Timer.

I'm planning on making Timer the default in the next version, but right now Idle is still the default.

**Comment by MightyCreak** [comment]
Aaah I see! I thought it was a combination of the two settings: clean every 24h, but only when the browser is idle (to prevent using CPU while the user is actively using their browser).

You can close this issue if you want 😉

Thanks!
