### ISSUE TITLE
What Firefox-history is cleared?

### ISSUE THREAD

**Issue by petter-thorvaldsen** [Rayquaza01/HistoryCleaner#39]
Thanks for a great addon. In Firefox settings, Clear Recent History, I have chosen the following to be cleared: 
History
> Browsing & download history YES, 
> Active logins NO, 
> Form & search history NO, 
> Cookies NO, 
> Cache YES, 
Data
> Site settings NO, 
> Offline website data YES. 
These settings are chosen to prevent logout or loosing context. Will the HistoryCleaner addon respect these settings, and in my case only clear Browsing & download history, Cache, Offline website data? Or will all history (older than x days) be cleared/deleted by HistoryCleaner? 
Thanks for your help. 
Regard, Petter Thorvaldsen

**Comment by Rayquaza01** [comment]
History Cleaner only clears browsing history. I'm looking into adding the ability to clear download history, but that isn't in the extension yet.

There is no API for clearing old cache, only recent cache (see #38). So History Cleaner can't clear cache, cookies, etc.

**Comment by petter-thorvaldsen** [comment]
Thanks for quick feedback. 

Rayquaza01: “History Cleaner only clears browsing history”, and from #38: “history.deleteRange() is what history cleaner uses. It allows you to specify a date range and delete all visits within that range”. 

Please specify which of these that History Cleaner deletes (older than x days): 
HISTORY: 
Browsing & download history? 
Active logins? 
Form & search history? 
Cookies? 
Cache? 
DATA: 
Site settings? 
Offline website data? 

I need to know so I can plan the use of History Cleaner. Thanks. 
Regards, Petter

**Comment by Rayquaza01** [comment]
Browsing & download history?: Yes. Browsing history only. Download history will be added in the future.
Active logins? No
Form & search history? No
Cookies? No
Cache? No
DATA:
Site settings? No
Offline website data? No
