### ISSUE TITLE
Clarification about description

### ISSUE THREAD

**Issue by swexpert** [Rayquaza01/HistoryCleaner#4]
Dear Developer(s),
Thank you for an awesome product! 
I have used the addon once or twice but both times had a hard time understanding the descriptive lines:
"Set the number of days to keep history items in the options page. Setting it to 0 will disable history deletion"

Does Setting it to 0 will disable the history deletion add-on or will it retain the history forever (bloating the places.sqlite file) until manually deleted? 

You might want to change these lines correspondingly at all the places to put it more clearly.

Thanks and keep up the good work!

Sincerely,
Inderjeet

**Comment by Rayquaza01** [comment]
Hello,
Sorry about the confusion. Setting it to 0 only prevents this extension from deleting history. Having the setting default to 0 (disabled) means the extension won't delete anything until the user sets their preferred number of days.

This extension can't (and won't) prevent you from deleting history through other means.

Hope this helps!
