### ISSUE TITLE
Does it support chrome?

### ISSUE THREAD

**Issue by snowman** [Rayquaza01/HistoryCleaner#6]
If not, do you have any plans to develop Chrome version?

**Comment by Rayquaza01** [comment]
Hello,
There is now a Chrome version now. You can find it here: https://chrome.google.com/webstore/detail/history-cleaner/epoabannnmjdknejdggkgjoebomipene/

The Chrome version (1.3.0) is newer than the Firefox version for the time being while Mozilla reviews the new version for Firefox.

**Comment by snowman** [comment]
Thanks, happy new year :heart:
